version: '3.8'

services:
  chatgpt-logger:
    build: .
    ports:
      - "3004:3004"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    networks:
      - trafficlog

networks:
  trafficlog:
    driver: bridge
