version: '3.8'

services:
  app:
    build: .
    ports:
      - "65030:3004"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    networks:
      - trafficlog

networks:
  trafficlog:
    driver: bridge
